A {
	TEXT-DECORATION: underline
}
#siteNotice {
	FONT-STYLE: italic; MARGIN-TOP: 5px; PADDING-LEFT: 4px; TEXT-ALIGN: center
}
#p-cactions {
	WIDTH: 80%
}
#content {
	BACKGROUND: #f8fcff
}
.ns-0  #content {
	BACKGROUND: white
}
#mytabs LI {
	BACKGROUND: #f8fcff
}
.ns-0  #mytabs LI {
	BACKGROUND: white
}
#mytabs LI A {
	BACKGROUND-COLOR: #f8fcff
}
.ns-0  #mytabs LI A {
	BACKGROUND-COLOR: white
}
#p-cactions LI {
	BACKGROUND: #f8fcff
}
.ns-0  #p-cactions LI {
	BACKGROUND: white
}
#p-cactions LI A {
	BACKGROUND-COLOR: #f8fcff
}
.ns-0  #p-cactions LI A {
	BACKGROUND-COLOR: white
}
#siteSub {
	DISPLAY: inline; FONT-SIZE: 120%; FONT-WEIGHT: normal
}
#bodyContent #siteSub A {
	BACKGROUND-COLOR: transparent; BACKGROUND-IMAGE: none; COLOR: #000; PADDING-RIGHT: 0px; TEXT-DECORATION: none
}
#ca-edit A {
	FONT-WEIGHT: bold! important
}
DIV.alreadyloggedin {
	COLOR: red; FONT-WEIGHT: bold
}

@media Print    
{
.editlink {
	DISPLAY: none
}
.noprint {
	DISPLAY: none
}
.metadata {
	DISPLAY: none
}
.dablink {
	DISPLAY: none
}
    }
#p-logo A {
	BACKGROUND-IMAGE: url(http://upload.wikimedia.org/wikipedia/en/b/bc/Wiki.png)! important
}
.notice {
	MARGIN: 1em 0.5em; PADDING-BOTTOM: 0.5em; PADDING-LEFT: 0.5em; PADDING-RIGHT: 0.5em; PADDING-TOP: 0.5em; TEXT-ALIGN: justify
}
#disambig {
	BORDER-BOTTOM: #cccccc 3px double; BORDER-TOP: #cccccc 3px double
}
.diffchange {
	FONT-WEIGHT: bold
}
TD.diff-addedline {
	FONT-SIZE: 85%
}
TD.diff-deletedline {
	FONT-SIZE: 85%
}
TD.diff-context {
	FONT-SIZE: 85%
}
